<h1>Python libraries for data analysis</h1>


<li><b><span style="color:blue">Numpy</span></b>: supports numerical and array operations
<li><b><span style="color:blue">Scipy</span></b>: open source library for mathematics and scientific computing
<li><b><span style="color:blue">Pandas</span></b>: supports data manipulation and analysis
<li><b><span style="color:blue">Visualization libraries</span></b>: matplotlib, seaborne, bokeh, plotly, gmplot, and many others provide support for charts and graphs

<h1>numpy</h1>


<h2>Why numpy?</h2>
<li>Multi-dimensional arrays:
<li>Faster and more space efficient than lists 
<li>Can incorporate C/C++/Fortran code
<li>Linear algebra, Fourier transforms, Random number support



<h2>numpy array</h2>

In [1]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(type(ax))
ax

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

<li>A numpy array has a data type associated with its elements
<li>and elements need to be of the same data type
<li>But an element could be an 'arbitrarily' complex object

In [2]:
np.array(['1','2',False])

array(['1', '2', 'False'], dtype='<U5')

In [2]:
ax = np.arange(18).reshape(6,3)
ax[3:5, 1:3]

array([[10, 11],
       [13, 14]])

In [3]:
midt = np.array([67,47.5,34,81,84.5,82,89,83,71,94,80.5,67.5,88,93,78,76,75,45,79,87.5,65,82,50,76,81,79,68,52,68,70,73,80,73.5,85,79,72,74,64,88,66,75,86,72,77,84,75,97,54,85,50,66.5,82,74,69.5,51,86])

In [4]:
print(midt.max(),midt.min(),midt.mean(),midt.std())

97.0 34.0 73.78571428571429 13.102909008681848


<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

<h4>The <i>dtype</i> attribute</h4>
<li>Stores the data type in the array
<li>numpy makes a best guess of the data type

In [6]:
ax = np.array([[1,2,3,4],[5,6,7,8.3]])
# ax.dtype
# print(ax.shape)
ax.shape

(2, 4)

In [8]:
ax = np.array([{'a':1,'b':2},4])
print(ax)
ax.dtype

[{'a': 1, 'b': 2} 4]


dtype('O')

In [10]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<li>The <i>astype</i> function converts from one type to another


In [8]:
ax = np.array([1,2,3,'4'])
print(ax.dtype)
ax.astype(int)

<U21


array([1, 2, 3, 4])

In [9]:
ay = ax.astype(np.float128)
print(ay)
ay.dtype

[1. 2. 3. 4.]


dtype('float128')

<h2>Basic operations</h2>

<h4>statistical operations</h4>

In [10]:
x = np.array([13,24,21.2,17.6,21.7],'float')
# several algebra functions for array: .sum(), .mean(), .std()
# print(,sep='\n')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h4>arrray arithmetic operations</h4>
<li><b>Important</b>: Arrays must be the same size!

In [11]:
# we can specify the type of array's item by adding a parameter follows that
x = np.array([13,24,21.2,17.6,21.7],'float')
y = np.array([1,3,4,7,2],'float')
x - y

array([12. , 21. , 17.2, 10.6, 19.7])

In [12]:
x+y

array([14. , 27. , 25.2, 24.6, 23.7])

In [13]:
x*y

array([ 13. ,  72. ,  84.8, 123.2,  43.4])

In [14]:
x/y

array([13.        ,  8.        ,  5.3       ,  2.51428571, 10.85      ])

<h2>Multi-dimensional arrays</h2>

In [7]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,'float')
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [8]:
ax[1:,3:] #indexing

array([[13., 14., 15.],
       [23., 24., 25.]])

In [10]:
ax = np.arange(1,19).reshape(6,3)
ax

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
ax = np.arange(1,19).reshape(6,3)
ax[(2,0), (1,2)]
# ax

array([8, 3])

In [6]:
ax[(0,2),(0,5)] # it is like matching two coordinates -- 0 and 0, 2 and 5

array([ 0., 25.])

<h3>Slicing</h3>

In [7]:
ax[1:3,2:4]
#Intersection between ax[1:3,:] and ax[:,2:4]

array([[12., 13.],
       [22., 23.]])

In [8]:
ax[[1,2],[2,3]] # how is this different with the previous one?
# the same as ax[(1,2), (2,3)]

array([12., 23.])

In [9]:
ax[(1,2), (2,3)]

array([12., 23.])

In [20]:
a = np.arange(0,10,1)
# a[2:10]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<h3>Reshaping</h3>
<li>nd arrays can be reshaped as long as the total dimensionality is unchanged


In [10]:
print(ax)
print(ax.shape)
ax.reshape(9,2)
# ax.reshape(10,3)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]
(3, 6)


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])

<h3>Creating nd arrays</h3>

<h4>Using the <i>array</i> function</h4>

In [22]:
data = [[0,1,2,3,4],[5,6,7,8,9]]
data_array = np.array(data)
data_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h4>Using initializers</h4>

<li>The <i>arrange</i> (array range) function


In [23]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)]) # Be aware how this is regarded as a 2d array
print(ay)
ax.dtype

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


dtype('int64')

In [24]:
ax = np.arange(10)**2
print(ax)
type(ax)

[ 0  1  4  9 16 25 36 49 64 81]


numpy.ndarray

<li>The <i>ones</i> function creates an array of 1s (floats)

In [14]:
ax = np.ones([10,2])
len(ax)

10

In [25]:
ax = np.ones(10)
print(ax)
ax.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [12]:
ax = np.array([[1,2,3,4],[5,6,7,8]])
ay = np.ones_like(ax)
print(ay)
ax

[[1 1 1 1]
 [1 1 1 1]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# np.ones_like(ax), np.zeros_like(ax)
ay = np.zeros_like(ax)
ay

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

<li>The <i>identity(n)</i> function creates an identity matrix of order n

In [28]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<li>The function <i>empty</i> creates an "empty" array
<li>Values in the array are "garbage" values

In [29]:
np.empty([2,3],float)

array([[4.64824859e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

<h3>Matrix multiplication</h3>


In [13]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [14]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h2>Lists vs numpy arrays</h2>
<li>Lists are heterogenous. Elements of a list can be of multiple types
<li>Numpy arrays are homogeneous. Elements can be of only one type
<li>Both are mutable
<li>Homogeneity makes indexed access faster and more memory efficient
<li>numpy are optimized for matrix operations
<li>numpy provides random number support


<h3>numpy arrays are homogeneous</h3>

<h3>numpy arrays are faster</h3>

In [32]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]])

<h4>Functionalize this</h4>


In [3]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    print(ax)
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]


datetime.timedelta(microseconds=19847)

<h4>Do the same with python lists</h4>


In [34]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10)

datetime.timedelta(microseconds=12)

<h4>Compare the two</h4>

In [35]:
for n in [10,100,1000,10000,1000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00.000022	0:00:00.000015
100	0:00:00.000012	0:00:00.000038
1000	0:00:00.000011	0:00:00.000407
10000	0:00:00.000035	0:00:00.005772
1000000	0:00:00.005215	0:00:01.188531


<h3>numpy indexing vs list indexing</h3>
<li>numpy arrays use direct indexing
<li>lists use chained indexing

In [22]:
ax = np.array([1,2,3,4,8,9])
x = [1,2,3,4,8,9]

#Extract the first and last elements from the numpy array into a single array
print(ax[[0, -1]])

#Extract the first and last elements from the list into a new list
#[x[0],x[-1]]

[1 9]


<h3>numpy slicing vs list slicing</h3>

In [37]:
ax = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
ax[1:3,1:3]


array([[22, 23],
       [32, 33]])

In [38]:
ax

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [39]:
lx = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]
#HELP!

<h2>batch operations on nd arrays</h2>
<li>numpy arrays allow the application of batch operations on all elements of an array
<li>without having to write a for loop or use an iterator
<li>by <i>vectorizing</i> operations, numpy is much faster than the slow for loop structure of python


<h3>batch: selecting elements using a boolean mask</h3>
<li> A boolean max applies a condition to each element in turn
<li> And returns an array of boolean with
<ul>
<li> True for each value that satisfies the condition
<li> False for every other value

In [17]:
ax = np.array([1,4,7,9,2,3,10,11,34,2])
ax < 7

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

<h4>The mask can be applied as a selection operator on the array

In [18]:
ax[ax<7]

array([1, 4, 2, 3, 2])

<h4>The mask doesn't have to be constructed on the same array</h4>
<li>But the mask and the array should have the same dimensions

In [20]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
names[bonus > 130000]
# check how the masks can be applied across arrays

array(['Bill', 'Sally'], dtype='<U8')

<h3>batch: arithmentic operations</h3>
<li>+, -, *, /, scalar multiplication do an element by element operation

In [21]:
ax = np.array([[1,2,3],[4,5,6]])
1/ax


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

<h3>batch: functional artithmetic operators</h3>

In [25]:
ax = np.array([4,9,2,4,0,25,0])
print(np.sum(ax>5))
print(np.count_nonzero(ax))
print(np.any(ax>10))
print(np.all(ax>0))

2
5
True
False


<h3>Logical operations with numpy</h3>
<li>logical_or
<li>logical_and

In [24]:
np.logical_and(bonus>90000.0, bonus<400000 )

array([ True, False, False,  True, False])

In [27]:
names[(bonus > 90000) & (bonus < 400000)]

array(['Bill', 'Savitri'], dtype='<U8')

<h4>Boolean operators</h4>
<li>the numpy equivalent of "and" is "&"
<li>the numpy equivalent of "or" is "|"
<li>the numpy equivalent of "not" is "!"


In [31]:
print(np.sum(bonus[(bonus>50000) & (bonus < 200000)]))
print(np.std(bonus[(names == 'Sally') | (names != 'Qing')]))
print(np.sum(bonus[(names=="Bill") | (names == "Qing")]))
print(np.sum(bonus[(names!="Bill")]))
print(np.sum(bonus[~((names=="Bill") | (names == "Qing"))]))


150135.86
165641.21099354434
236191.8
632150.55
628259.31


<b>Problem</b> Calculate the mean and median bonus anount for all female employees with bonus less than $100,000

In [13]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])



In [14]:
np.mean(bonus[(gender == 'F') & (bonus < 100000)])

50951.8

<b>Problem</b> Return an nd array containing the named of all female employees with bonus less than $100,000

In [49]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])


<h3>batch: Selecting elements using where</h3>
<li><i>where</i> function creates a new array using a conditional expression
<li>Somewhat like the if function in an excel spreadsheet

In [50]:
np.where(names == 'Bill',1,0)

array([1, 0, 0, 0, 0])

<h2>axes</h2>
<li>The axis parameter tells numpy which axis to operate along

In [34]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ax = ax.reshape(3,4)
print(ax.shape)
print(ax)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h4>sum each column</h4>

In [52]:
ax.sum(axis=0)

array([15, 18, 21, 24])

<h4>sum each row</h4>

In [53]:
ax.sum(axis=1)

array([10, 26, 42])

<h4>sum by depth</h4>

In [54]:
ax=ax.reshape(2,3,2)
ax.sum(axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])

<h4>add an axis to an array</h4>


In [28]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ax, ax.shape)
# here the shape would be (12,) since it only has one dimension, comma denotes nothing followed by that
# print(ax.reshape(1,12))
ay = ax[:,np.newaxis]
print(ay, ay.shape)
az = ax[np.newaxis,:]
print(az,az.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (12, 1)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]] (1, 12)


In [10]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ax.shape
print(ax[np.newaxis])
print(ax)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


<h4>Easy to add n-dimensions to an nd array using newaxis</h4>

In [57]:
ax = ax.reshape(4,3)
ax[np.newaxis,np.newaxis,np.newaxis,:,:]

array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]]])

In [58]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
# pay attention to the use of where
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

<h2>Broadcasting</h2>
<li>arithmetic operations work element by element
<li>so both arrays have to be of the same length
<li><b>broadcasting</b> is used for arithmetic on arrays of different shapes

In [59]:
ax = np.array([1,2,3])
ay = np.array([3,2,1])
ax+ay

array([4, 4, 4])

<li>when one operand is a scalar, numpy works as if it has created a second array
<li>ax + 5 is equivalent to ax + np.array([5,5,5,])
<li>note the "as if" because it doesn't actually do that
<li>instead it <b>broadcasts</b> the 5 to each element of ax
<li>we can do this broadcasting on any dimensional array

In [60]:
ay = np.ones([3,3])
ay

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
ax = np.array([1,2,3])
ax + ay

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

<b>broadcasting</b> won't work when arrays are of incompatible dimensions

In [2]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

ay = np.array([3,4,5])


print(ax[:,np.newaxis])


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
print(ax[:,np.newaxis] + ay)# its (1,12) + (3,1)
print(ax[:,np.newaxis])

[[ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


<h4>np.newaxis is useful here because we can convert ax into a 2D array</h4>

In [52]:
ax[:,np.newaxis] + ay

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

In [65]:
#Broadcasting effectively does this:
ax[:,np.newaxis] + np.array([[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5]])

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

<h4>We could also convert ay into a 2D array</h4>
<li>the result will be different (why?) 

In [66]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay[:,np.newaxis]

array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]])

<h2>Fancy indexing</h2>
<li>numpy let's us work on indexed subsets of an nd array
<li>this lets us construct arbitrary subsets of an nd array in any dimension

In [67]:
ax = np.array([4,3,9,2,1,6])
ay = np.array([2,4])
ax[ay]

array([9, 1])

In [68]:
ay = np.array([[2,4],[1,3]])
ax[ay]

array([[9, 1],
       [3, 2]])

<h4>multi-dimentional indexes</h4>
<li>In a 2-d, index, the index array is used to generate (row_number,col_number) pairs

In [69]:
ax = np.array([[23,34,21,34,22],[33,44,11,29,32],[14,90,10,20,17]])
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] # [ax[0,1],ax[2,4]]

array([34, 17])

In [70]:
ax

array([[23, 34, 21, 34, 22],
       [33, 44, 11, 29, 32],
       [14, 90, 10, 20, 17]])

In [71]:
rows2 = np.array([[0,0],[2,2]])
cols2 = np.array([[0,4],[0,4]])
ax[rows2,cols2]

array([[23, 22],
       [14, 17]])

In [72]:
ax[1:3,[2,3,4]]

array([[11, 29, 32],
       [10, 20, 17]])

In [73]:
ax[0:3:2,0:5:4]

array([[23, 22],
       [14, 17]])

In [74]:
# ax.reshape(5,3)

<h2>Universal functions</h2>
<li>functions that perform elementwise operations on arrays
<li>fast "wrapper" functions that produce scalar (or lower dimension) results
<li>sqrt, exp, add,maximum, minimum, abs, etc.
<li>https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [11]:
ax = np.array([1,2,3,4,5,6,7],float)
np.sqrt(ax)
np.exp(ax)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [12]:
ay = np.arange(10,17)
np.add(ax,ay)
np.maximum(ax,ay)

array([10., 11., 12., 13., 14., 15., 16.])

In [77]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [78]:
import scipy
scipy.nanmean(x)

<ipython-input-78-323a47b69711>:2: DeprecationWarning: scipy.nanmean is deprecated and will be removed in SciPy 2.0.0, use numpy.nanmean instead
  scipy.nanmean(x)


12.5

<h3>Random number support in numpy</h3>

In [79]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([-1.53907459, -1.21337694, -0.04993444, -1.3276927 , -0.95601297,
       -1.28772498,  1.8485916 , -0.06770803, -0.32613141, -0.84073173])

In [18]:
np.random.normal(0, 1, 1000)

array([ 2.57973618e-01, -2.21769601e+00,  1.08563070e+00,  4.27487931e-01,
        3.95341375e-01,  1.37695196e+00,  1.95156502e+00, -3.56138447e-01,
       -3.38998061e-02,  3.17932614e-01,  5.50741870e-01, -1.19184684e-01,
       -1.15388239e+00,  8.76151087e-01,  1.58120732e-01, -2.69296010e-01,
        3.72433554e-01, -1.04424752e+00, -5.38280500e-01, -1.06860013e+00,
        1.29451277e+00,  7.90041211e-01, -1.06270981e-01,  1.84212977e-01,
        2.18566130e-01,  1.54683172e+00,  1.19841591e+00, -1.31344624e-01,
       -7.53881687e-01,  1.09075395e+00,  1.15185493e+00, -6.89035695e-01,
        1.32487465e+00, -2.60967212e-02,  2.37579430e-02, -6.31111866e-01,
        8.33151751e-01, -8.45994276e-01,  5.48626656e-01,  5.45024220e-01,
        4.46916951e-01,  1.43988279e+00,  9.41255991e-01, -2.25067891e-02,
        4.48751399e-01,  1.45800729e+00,  1.73999526e+00, -1.64735188e-02,
        1.21040040e+00, -6.06753459e-02, -5.29275968e-02,  5.38987769e-01,
        2.70112166e-01,  